@TantareApi_HostAddress = https://localhost:7024

POST {{TantareApi_HostAddress}}/worlds
Content-Type: application/json

{
  "Id": 1,
  "Name": "Tantare"
}

###

@id=1
GET {{TantareApi_HostAddress}}/worlds/{{id}}

###

GET {{TantareApi_HostAddress}}/worlds

###
