@TantareApi_HostAddress = https://localhost:7024



POST {{TantareApi_HostAddress}}/worlds
Content-Type: application/json

{
    "Id": 1,
    "Name": "Tantare"
}

###

GET {{TantareApi_HostAddress}}/worlds

###

GET {{TantareApi_HostAddress}}/worlds/1

###
